### ISSUE TITLE
IS 01 | MkDocs - Ajustar configurações

### ISSUE THREAD

**Issue by ArthurFerreiraRodrigues** [ResidenciaTICBrisa/T2G4-Querido-Diario#1]
- [x] Ajustar configurações da documentação
- [x] Definir estrutura dos arquivos
- [ ] Ajustar workflow de deploy

**Comment by raissamsoliveira** [comment]
@ArthurFerreiraRodrigues @esteerlino estou movendo a issue para a Etapa de Finalizado.
