### ISSUE TITLE
IS 10 | Criação do documento de Fluxo de Dados

### ISSUE THREAD

**Issue by wildemberg-sales** [ResidenciaTICBrisa/T2G4-Querido-Diario#10]
Criação do documento de fluxo de dados que conta com a infraestrutura detalhada do projeto com o fluxo bem explicado dos dados, desde onde é raspado, os caminhos que ele passa dentro dos repositórios e ferramentas, até a chegada ao usuário.
[Link para o diagrama](https://drive.google.com/file/d/1UT-d6LR2DxSDPvKKfSjWzBb_JOdUgy5n/view?usp=sharing)

**Comment by raissamsoliveira** [comment]
**Fluxo de Dados finalizado**



![Image](https://github.com/ResidenciaTICBrisa/T2G4-Querido-Diario/assets/113456598/2d2bbb4e-e4b3-4f86-83ad-8bbb99e839cd)
