### ISSUE TITLE
IS 16 | Criar protótipo da interface do site para a US-1

### ISSUE THREAD

**Issue by esteerlino** [ResidenciaTICBrisa/T2G4-Querido-Diario#16]
Criar protótipo da interface para a US-1

**Descrição**
O protótipo fornece uma representação visual e funcional do produto final antes de iniciar o desenvolvimento. Ele permite que os stakeholders visualizem antecipadamente o resultado e possam contribuir com feedbacks.

**Tarefas** 
- [x] Criar protótipo no Figma

**Observação**
- Esse protótipo precisa ser aprovado pelo cliente.

**Comment by esteerlino** [comment]
Link para visualização do protótipo:

https://www.figma.com/file/PTRrSgLiz6DOlkYwA3Tt6Q/Prot%C3%B3tipo-para-a-p%C3%A1gina-%22Tecnologia-na-Educa%C3%A7%C3%A3o%22?type=design&node-id=0%3A1&mode=design&t=qLVxL28ZovHD5bag-1

**Comment by wildemberg-sales** [comment]
Por favor, libera o acesso público ao link por favor

**Comment by esteerlino** [comment]
Link substituído!

**Comment by csafurtado** [comment]
Movi o card para revisão porque já enviei para o cliente revisar!
