### ISSUE TITLE
IS 17 | Criar protótipo da interface do site para a US-2

### ISSUE THREAD

**Issue by pkbceira03** [ResidenciaTICBrisa/T2G4-Querido-Diario#17]
Criar protótipo da interface para a US-2

**Descrição**
O protótipo fornece uma representação visual e funcional do produto final antes de iniciar o desenvolvimento. Ele permite que os stakeholders visualizem antecipadamente o resultado e possam contribuir com feedbacks.

**Tarefas** 
- [ ] Criar protótipo no Figma

**Observação**
- Esse protótipo precisa ser aprovado pelo cliente.

**Comment by ArthurFerreiraRodrigues** [comment]
Acesse o [Figma](https://www.figma.com/file/PTRrSgLiz6DOlkYwA3Tt6Q/Prot%C3%B3tipo-para-a-p%C3%A1gina-%22Tecnologia-na-Educa%C3%A7%C3%A3o%22?type=design&node-id=0-1&mode=design).
