### ISSUE TITLE
IS 18 | Documentando erros da Configuração do Ambiente

### ISSUE THREAD

**Issue by raissamsoliveira** [ResidenciaTICBrisa/T2G4-Querido-Diario#18]
**Documentando erros da Configuração do Ambiente**

**Descrição**
Durante a configuraç]ao do ambiente, inúmeros erros vem sendo encontrados, sem nenhuma resolução - até o momento. Por esse motivo, decidimos documentar todo esse processo para, em seguida, tentar resolver os erros encontrados contribuindo para a comunidade do Querido Diário como um todo. 

**Tarefas** 
- [ ] Criar documento padrão para que todos possam contribuir;
- [ ] Indicar todos os erros encontrados durante a configuração do ambiente e possíveis soluções. 

***Requisitos:***
- SO: Linux
- Clone de todos os repositórios que são necessários

**Comment by csafurtado** [comment]
Adicionar observação sobre erro de portas que ocorre em alguns casos quando se levanta o ambiente do data-processing

**Comment by csafurtado** [comment]
![Image](https://github.com/ResidenciaTICBrisa/T2G4-Querido-Diario/assets/77639735/841a6397-f95a-4cb2-9090-00801fcfcc7a)
