### ISSUE TITLE
IS 03 | Repo - Definir padrões de contribuição

### ISSUE THREAD

**Issue by ArthurFerreiraRodrigues** [ResidenciaTICBrisa/T2G4-Querido-Diario#3]
- [x] Padrão de mensagem de commit
- [x] Padrão de título de PR
- [x] Padrão de título de issue
- [x] Criar template de issues
- [x] Criar template de PR
- [x] CONTRIBUTING.md

**Comment by raissamsoliveira** [comment]
O template dos PR's utilizados serão os mesmos da OKBR.

**Comment by esteerlino** [comment]
O padrão das mensagens dos commits seguirá o guia de contribuição do Querido Diário.
