### ISSUE TITLE
IS 38 | Solucionar bugs encontrados com PR das US1 e US2

### ISSUE THREAD

**Issue by csafurtado** [ResidenciaTICBrisa/T2G4-Querido-Diario#38]
**Descrição**
Resolver os bugs e detalhes encontrados pelo cliente sobre o PR enviado.

**Tarefas** 
- [x] História dos commits confusa: ajustar commits relacionados a essa cada funcionalidade, pois tem muitos commits (talvez usar um merge ou squash)
- [ ] Botão de "Baixar selecionados" só aparece quando logado no QD-Edu e deveria aparecer sempre.
- [x] Elementos deveriam indicar que são clicáveis (mãozinha) e terem efeitos ao clicar(quais efeitos?)
- [x] Retirar alerta do botão de download do Portal Geral. Basta o botão não ser clicável sem excertos selecionados.
- [x] Colocar 'Todos' à esquerda do botão de baixar no Portal Geral e mudar texto para 'Selecionar Todos'.
- [x] Colocar cor do botão e cor do check selecionado com cores iguais (#FF8200)
- [x] Ver vídeo de bugs sobre contagem de excertos selecionados.
- [x] Retirar checkbox duplicado nos excertos da página do QD-Geral

***Observações:***
* As cores dos checks e dos botões precisaram ser assim por conta do check ficar preto se for colocado igual
* Não é possível ver o vídeo mostrando os bugs dentro dos comentários do PR

**Comment by raissamsoliveira** [comment]
As correções relativas a US-1 já foram realizadas.
