### ISSUE TITLE
IS 08 | Documentar o processo de subida do ambiente

### ISSUE THREAD

**Issue by raissamsoliveira** [ResidenciaTICBrisa/T2G4-Querido-Diario#8]
**Documentar o processo de subida do ambiente**

**Descrição**
O time por inteiro não está conseguindo subir e preparar o ambiente de trabalho, pois a documentação do Querido Diário está incorreta, e vários erros estão surgindo. Decidimos, então, documentar todo esse processo para facilitar para todas as pessoas que decidirem contribuir com o Querido Diário. Os registros ficarão em nossa documentação. 

**Tarefas** 
- [x] Registrar cada erro encontrado

**Comment by wildemberg-sales** [comment]
Adicionar o link do documento aqui para ficar registrado

**Comment by raissamsoliveira** [comment]
**Tutorial atualizado para configuração do ambiente** 



- [Tutorial de ambiente.pdf](https://github.com/ResidenciaTICBrisa/T2G4-Querido-Diario/files/14762255/tutorial_ambiente_completo_qd.3.pdf)
